### ISSUE TITLE
 Submit Form ( POST ) after confirmation

### ISSUE THREAD

**Issue by marcoczen** [HTMLGuyLLC/jConfirm#1]
Hi,

I have a bootstrap form with a submit button as below;

``
<button type="submit" class="btn btn-primary" name="button_deluser"  > Delete Selected User </button>
``

When the button is clicked - the form is submitted. I would like a confirmation box (Yes - Delete, No ).
I dont understand how to incorporate jConfirm into the button above from the documentation provided.

Any ideas ? Alert - Jquery newbie here.

**Comment by marcoczen** [comment]
Bump

**Comment by HTMLGuyLLC** [comment]
Wow. Over a year ago and I'm just seeing this. I'm sure by now you're a jQuery genius. How's it going?

**Comment by HTMLGuyLLC** [comment]
I completely rebuilt the plugin FYI. You should really check it out.
