### ISSUE TITLE
Webpack minification problem

### ISSUE THREAD

**Issue by tnusraddinov** [HTMLGuyLLC/jConfirm#7]
Hi thanks for your library, but I have a problem with minification using webpack it says:
```
ERROR in main.2465bbd007eb4bee4c62.js from UglifyJs
Unexpected token: name (helper) [main.2465bbd007eb4bee4c62.js:67980,12]
```
I tried these imports but it gives error:
```
require('jconfirm/jConfirm') or
import 'jconfirm/jConfirm'
```
Do you know how to use it with webpack. Can you help me?

**Comment by HTMLGuyLLC** [comment]
I haven't used jConfirm with webpack yet, but I believe it would be
`const jconfirm = require('jconfirm');`
Try that and let me know!

**Comment by tnusraddinov** [comment]
Just tried now it says:

```
ERROR in main.307931e5f4784ae190b0.js from UglifyJs
Unexpected token: name (d) [main.307931e5f4784ae190b0.js:67953,288]
```

**Comment by HTMLGuyLLC** [comment]
I just remembered I never really set this up to work correctly with webpack. It's hacktoberfest...do you want to submit a pull request modifying it? You'll just need to create a new entry point. If not, I'll get to it, but probably not today. I suggest you just include the plugin as a script tag if you can't wait.

**Comment by tnusraddinov** [comment]
Changing webpack version from 3 to 4 solved this problem.

**Comment by HTMLGuyLLC** [comment]
Interesting, thanks for letting me know
